// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/messages.proto

package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Employee struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BadgeNumber          int32    `protobuf:"varint,2,opt,name=badgeNumber,proto3" json:"badgeNumber,omitempty"`
	FirstName            string   `protobuf:"bytes,3,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,4,opt,name=lastName,proto3" json:"lastName,omitempty"`
	VacationAccrualRate  float32  `protobuf:"fixed32,5,opt,name=vacationAccrualRate,proto3" json:"vacationAccrualRate,omitempty"`
	VacationAccrued      float32  `protobuf:"fixed32,6,opt,name=vacationAccrued,proto3" json:"vacationAccrued,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Employee) Reset()         { *m = Employee{} }
func (m *Employee) String() string { return proto.CompactTextString(m) }
func (*Employee) ProtoMessage()    {}
func (*Employee) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_3343ef3584f65132, []int{0}
}
func (m *Employee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Employee.Unmarshal(m, b)
}
func (m *Employee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Employee.Marshal(b, m, deterministic)
}
func (dst *Employee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Employee.Merge(dst, src)
}
func (m *Employee) XXX_Size() int {
	return xxx_messageInfo_Employee.Size(m)
}
func (m *Employee) XXX_DiscardUnknown() {
	xxx_messageInfo_Employee.DiscardUnknown(m)
}

var xxx_messageInfo_Employee proto.InternalMessageInfo

func (m *Employee) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Employee) GetBadgeNumber() int32 {
	if m != nil {
		return m.BadgeNumber
	}
	return 0
}

func (m *Employee) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Employee) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Employee) GetVacationAccrualRate() float32 {
	if m != nil {
		return m.VacationAccrualRate
	}
	return 0
}

func (m *Employee) GetVacationAccrued() float32 {
	if m != nil {
		return m.VacationAccrued
	}
	return 0
}

type GetAllrequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllrequest) Reset()         { *m = GetAllrequest{} }
func (m *GetAllrequest) String() string { return proto.CompactTextString(m) }
func (*GetAllrequest) ProtoMessage()    {}
func (*GetAllrequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_3343ef3584f65132, []int{1}
}
func (m *GetAllrequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllrequest.Unmarshal(m, b)
}
func (m *GetAllrequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllrequest.Marshal(b, m, deterministic)
}
func (dst *GetAllrequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllrequest.Merge(dst, src)
}
func (m *GetAllrequest) XXX_Size() int {
	return xxx_messageInfo_GetAllrequest.Size(m)
}
func (m *GetAllrequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllrequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllrequest proto.InternalMessageInfo

type GetByBadgeNumberRequest struct {
	BadgeNumber          int32    `protobuf:"varint,1,opt,name=badgeNumber,proto3" json:"badgeNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByBadgeNumberRequest) Reset()         { *m = GetByBadgeNumberRequest{} }
func (m *GetByBadgeNumberRequest) String() string { return proto.CompactTextString(m) }
func (*GetByBadgeNumberRequest) ProtoMessage()    {}
func (*GetByBadgeNumberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_3343ef3584f65132, []int{2}
}
func (m *GetByBadgeNumberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByBadgeNumberRequest.Unmarshal(m, b)
}
func (m *GetByBadgeNumberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByBadgeNumberRequest.Marshal(b, m, deterministic)
}
func (dst *GetByBadgeNumberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByBadgeNumberRequest.Merge(dst, src)
}
func (m *GetByBadgeNumberRequest) XXX_Size() int {
	return xxx_messageInfo_GetByBadgeNumberRequest.Size(m)
}
func (m *GetByBadgeNumberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByBadgeNumberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByBadgeNumberRequest proto.InternalMessageInfo

func (m *GetByBadgeNumberRequest) GetBadgeNumber() int32 {
	if m != nil {
		return m.BadgeNumber
	}
	return 0
}

type EmployeeRequest struct {
	Employee             *Employee `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EmployeeRequest) Reset()         { *m = EmployeeRequest{} }
func (m *EmployeeRequest) String() string { return proto.CompactTextString(m) }
func (*EmployeeRequest) ProtoMessage()    {}
func (*EmployeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_3343ef3584f65132, []int{3}
}
func (m *EmployeeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmployeeRequest.Unmarshal(m, b)
}
func (m *EmployeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmployeeRequest.Marshal(b, m, deterministic)
}
func (dst *EmployeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmployeeRequest.Merge(dst, src)
}
func (m *EmployeeRequest) XXX_Size() int {
	return xxx_messageInfo_EmployeeRequest.Size(m)
}
func (m *EmployeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmployeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmployeeRequest proto.InternalMessageInfo

func (m *EmployeeRequest) GetEmployee() *Employee {
	if m != nil {
		return m.Employee
	}
	return nil
}

type EmployeeResponse struct {
	Employee             *Employee `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EmployeeResponse) Reset()         { *m = EmployeeResponse{} }
func (m *EmployeeResponse) String() string { return proto.CompactTextString(m) }
func (*EmployeeResponse) ProtoMessage()    {}
func (*EmployeeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_3343ef3584f65132, []int{4}
}
func (m *EmployeeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmployeeResponse.Unmarshal(m, b)
}
func (m *EmployeeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmployeeResponse.Marshal(b, m, deterministic)
}
func (dst *EmployeeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmployeeResponse.Merge(dst, src)
}
func (m *EmployeeResponse) XXX_Size() int {
	return xxx_messageInfo_EmployeeResponse.Size(m)
}
func (m *EmployeeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmployeeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmployeeResponse proto.InternalMessageInfo

func (m *EmployeeResponse) GetEmployee() *Employee {
	if m != nil {
		return m.Employee
	}
	return nil
}

type AddPhotoRequest struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPhotoRequest) Reset()         { *m = AddPhotoRequest{} }
func (m *AddPhotoRequest) String() string { return proto.CompactTextString(m) }
func (*AddPhotoRequest) ProtoMessage()    {}
func (*AddPhotoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_3343ef3584f65132, []int{5}
}
func (m *AddPhotoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPhotoRequest.Unmarshal(m, b)
}
func (m *AddPhotoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPhotoRequest.Marshal(b, m, deterministic)
}
func (dst *AddPhotoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPhotoRequest.Merge(dst, src)
}
func (m *AddPhotoRequest) XXX_Size() int {
	return xxx_messageInfo_AddPhotoRequest.Size(m)
}
func (m *AddPhotoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPhotoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddPhotoRequest proto.InternalMessageInfo

func (m *AddPhotoRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type AddPhotoResponse struct {
	IsSuccess            bool     `protobuf:"varint,1,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPhotoResponse) Reset()         { *m = AddPhotoResponse{} }
func (m *AddPhotoResponse) String() string { return proto.CompactTextString(m) }
func (*AddPhotoResponse) ProtoMessage()    {}
func (*AddPhotoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_3343ef3584f65132, []int{6}
}
func (m *AddPhotoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPhotoResponse.Unmarshal(m, b)
}
func (m *AddPhotoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPhotoResponse.Marshal(b, m, deterministic)
}
func (dst *AddPhotoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPhotoResponse.Merge(dst, src)
}
func (m *AddPhotoResponse) XXX_Size() int {
	return xxx_messageInfo_AddPhotoResponse.Size(m)
}
func (m *AddPhotoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPhotoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddPhotoResponse proto.InternalMessageInfo

func (m *AddPhotoResponse) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

func init() {
	proto.RegisterType((*Employee)(nil), "proto.Employee")
	proto.RegisterType((*GetAllrequest)(nil), "proto.GetAllrequest")
	proto.RegisterType((*GetByBadgeNumberRequest)(nil), "proto.GetByBadgeNumberRequest")
	proto.RegisterType((*EmployeeRequest)(nil), "proto.EmployeeRequest")
	proto.RegisterType((*EmployeeResponse)(nil), "proto.EmployeeResponse")
	proto.RegisterType((*AddPhotoRequest)(nil), "proto.AddPhotoRequest")
	proto.RegisterType((*AddPhotoResponse)(nil), "proto.AddPhotoResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EmployeeServicesClient is the client API for EmployeeServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EmployeeServicesClient interface {
	GetByBadgeNumber(ctx context.Context, in *GetByBadgeNumberRequest, opts ...grpc.CallOption) (*EmployeeResponse, error)
	GetAll(ctx context.Context, in *GetAllrequest, opts ...grpc.CallOption) (EmployeeServices_GetAllClient, error)
	SaveEmployee(ctx context.Context, in *EmployeeRequest, opts ...grpc.CallOption) (*EmployeeResponse, error)
	SaveAll(ctx context.Context, opts ...grpc.CallOption) (EmployeeServices_SaveAllClient, error)
	AddPhoto(ctx context.Context, opts ...grpc.CallOption) (EmployeeServices_AddPhotoClient, error)
}

type employeeServicesClient struct {
	cc *grpc.ClientConn
}

func NewEmployeeServicesClient(cc *grpc.ClientConn) EmployeeServicesClient {
	return &employeeServicesClient{cc}
}

func (c *employeeServicesClient) GetByBadgeNumber(ctx context.Context, in *GetByBadgeNumberRequest, opts ...grpc.CallOption) (*EmployeeResponse, error) {
	out := new(EmployeeResponse)
	err := c.cc.Invoke(ctx, "/proto.EmployeeServices/getByBadgeNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeServicesClient) GetAll(ctx context.Context, in *GetAllrequest, opts ...grpc.CallOption) (EmployeeServices_GetAllClient, error) {
	stream, err := c.cc.NewStream(ctx, &_EmployeeServices_serviceDesc.Streams[0], "/proto.EmployeeServices/getAll", opts...)
	if err != nil {
		return nil, err
	}
	x := &employeeServicesGetAllClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type EmployeeServices_GetAllClient interface {
	Recv() (*EmployeeResponse, error)
	grpc.ClientStream
}

type employeeServicesGetAllClient struct {
	grpc.ClientStream
}

func (x *employeeServicesGetAllClient) Recv() (*EmployeeResponse, error) {
	m := new(EmployeeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *employeeServicesClient) SaveEmployee(ctx context.Context, in *EmployeeRequest, opts ...grpc.CallOption) (*EmployeeResponse, error) {
	out := new(EmployeeResponse)
	err := c.cc.Invoke(ctx, "/proto.EmployeeServices/saveEmployee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeServicesClient) SaveAll(ctx context.Context, opts ...grpc.CallOption) (EmployeeServices_SaveAllClient, error) {
	stream, err := c.cc.NewStream(ctx, &_EmployeeServices_serviceDesc.Streams[1], "/proto.EmployeeServices/saveAll", opts...)
	if err != nil {
		return nil, err
	}
	x := &employeeServicesSaveAllClient{stream}
	return x, nil
}

type EmployeeServices_SaveAllClient interface {
	Send(*EmployeeRequest) error
	Recv() (*EmployeeResponse, error)
	grpc.ClientStream
}

type employeeServicesSaveAllClient struct {
	grpc.ClientStream
}

func (x *employeeServicesSaveAllClient) Send(m *EmployeeRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *employeeServicesSaveAllClient) Recv() (*EmployeeResponse, error) {
	m := new(EmployeeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *employeeServicesClient) AddPhoto(ctx context.Context, opts ...grpc.CallOption) (EmployeeServices_AddPhotoClient, error) {
	stream, err := c.cc.NewStream(ctx, &_EmployeeServices_serviceDesc.Streams[2], "/proto.EmployeeServices/addPhoto", opts...)
	if err != nil {
		return nil, err
	}
	x := &employeeServicesAddPhotoClient{stream}
	return x, nil
}

type EmployeeServices_AddPhotoClient interface {
	Send(*AddPhotoRequest) error
	CloseAndRecv() (*AddPhotoResponse, error)
	grpc.ClientStream
}

type employeeServicesAddPhotoClient struct {
	grpc.ClientStream
}

func (x *employeeServicesAddPhotoClient) Send(m *AddPhotoRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *employeeServicesAddPhotoClient) CloseAndRecv() (*AddPhotoResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(AddPhotoResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EmployeeServicesServer is the server API for EmployeeServices service.
type EmployeeServicesServer interface {
	GetByBadgeNumber(context.Context, *GetByBadgeNumberRequest) (*EmployeeResponse, error)
	GetAll(*GetAllrequest, EmployeeServices_GetAllServer) error
	SaveEmployee(context.Context, *EmployeeRequest) (*EmployeeResponse, error)
	SaveAll(EmployeeServices_SaveAllServer) error
	AddPhoto(EmployeeServices_AddPhotoServer) error
}

func RegisterEmployeeServicesServer(s *grpc.Server, srv EmployeeServicesServer) {
	s.RegisterService(&_EmployeeServices_serviceDesc, srv)
}

func _EmployeeServices_GetByBadgeNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByBadgeNumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServicesServer).GetByBadgeNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EmployeeServices/GetByBadgeNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServicesServer).GetByBadgeNumber(ctx, req.(*GetByBadgeNumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeServices_GetAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetAllrequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EmployeeServicesServer).GetAll(m, &employeeServicesGetAllServer{stream})
}

type EmployeeServices_GetAllServer interface {
	Send(*EmployeeResponse) error
	grpc.ServerStream
}

type employeeServicesGetAllServer struct {
	grpc.ServerStream
}

func (x *employeeServicesGetAllServer) Send(m *EmployeeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _EmployeeServices_SaveEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmployeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServicesServer).SaveEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EmployeeServices/SaveEmployee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServicesServer).SaveEmployee(ctx, req.(*EmployeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeServices_SaveAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EmployeeServicesServer).SaveAll(&employeeServicesSaveAllServer{stream})
}

type EmployeeServices_SaveAllServer interface {
	Send(*EmployeeResponse) error
	Recv() (*EmployeeRequest, error)
	grpc.ServerStream
}

type employeeServicesSaveAllServer struct {
	grpc.ServerStream
}

func (x *employeeServicesSaveAllServer) Send(m *EmployeeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *employeeServicesSaveAllServer) Recv() (*EmployeeRequest, error) {
	m := new(EmployeeRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _EmployeeServices_AddPhoto_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EmployeeServicesServer).AddPhoto(&employeeServicesAddPhotoServer{stream})
}

type EmployeeServices_AddPhotoServer interface {
	SendAndClose(*AddPhotoResponse) error
	Recv() (*AddPhotoRequest, error)
	grpc.ServerStream
}

type employeeServicesAddPhotoServer struct {
	grpc.ServerStream
}

func (x *employeeServicesAddPhotoServer) SendAndClose(m *AddPhotoResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *employeeServicesAddPhotoServer) Recv() (*AddPhotoRequest, error) {
	m := new(AddPhotoRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _EmployeeServices_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.EmployeeServices",
	HandlerType: (*EmployeeServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getByBadgeNumber",
			Handler:    _EmployeeServices_GetByBadgeNumber_Handler,
		},
		{
			MethodName: "saveEmployee",
			Handler:    _EmployeeServices_SaveEmployee_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "getAll",
			Handler:       _EmployeeServices_GetAll_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "saveAll",
			Handler:       _EmployeeServices_SaveAll_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "addPhoto",
			Handler:       _EmployeeServices_AddPhoto_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/messages.proto",
}

func init() { proto.RegisterFile("proto/messages.proto", fileDescriptor_messages_3343ef3584f65132) }

var fileDescriptor_messages_3343ef3584f65132 = []byte{
	// 418 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xd1, 0x8a, 0xd3, 0x40,
	0x14, 0x65, 0xe2, 0xb6, 0xa6, 0x77, 0x57, 0x53, 0xc6, 0xc5, 0x0d, 0xeb, 0x22, 0x21, 0x20, 0x06,
	0x84, 0x18, 0xd6, 0x27, 0x11, 0x77, 0x69, 0x41, 0xf6, 0x41, 0x58, 0x24, 0xfb, 0xe6, 0xdb, 0x24,
	0xb9, 0xa6, 0x03, 0x49, 0xa6, 0x66, 0x26, 0x85, 0xf6, 0x33, 0x7d, 0xf4, 0x6b, 0xa4, 0xd3, 0x24,
	0xa3, 0xa9, 0x65, 0xe9, 0x53, 0x67, 0xce, 0x3d, 0xe7, 0xdc, 0x3b, 0xe7, 0x36, 0x70, 0xbe, 0xac,
	0x85, 0x12, 0xef, 0x4b, 0x94, 0x92, 0xe5, 0x28, 0x43, 0x7d, 0xa5, 0x23, 0xfd, 0xe3, 0xff, 0x22,
	0x60, 0x7f, 0x29, 0x97, 0x85, 0x58, 0x23, 0xd2, 0xe7, 0x60, 0xf1, 0xcc, 0x25, 0x1e, 0x09, 0x46,
	0xb1, 0xc5, 0x33, 0xea, 0xc1, 0x69, 0xc2, 0xb2, 0x1c, 0xef, 0x9b, 0x32, 0xc1, 0xda, 0xb5, 0x74,
	0xe1, 0x6f, 0x88, 0x5e, 0xc1, 0xe4, 0x07, 0xaf, 0xa5, 0xba, 0x67, 0x25, 0xba, 0x4f, 0x3c, 0x12,
	0x4c, 0x62, 0x03, 0xd0, 0x4b, 0xb0, 0x0b, 0xd6, 0x16, 0x4f, 0x74, 0xb1, 0xbf, 0xd3, 0x08, 0x5e,
	0xac, 0x58, 0xca, 0x14, 0x17, 0xd5, 0x2c, 0x4d, 0xeb, 0x86, 0x15, 0x31, 0x53, 0xe8, 0x8e, 0x3c,
	0x12, 0x58, 0xf1, 0xff, 0x4a, 0x34, 0x00, 0xe7, 0x1f, 0x18, 0x33, 0x77, 0xac, 0xd9, 0x43, 0xd8,
	0x77, 0xe0, 0xd9, 0x1d, 0xaa, 0x59, 0x51, 0xd4, 0xf8, 0xb3, 0x41, 0xa9, 0xfc, 0x4f, 0x70, 0x71,
	0x87, 0x6a, 0xbe, 0x9e, 0x9b, 0xd1, 0xe3, 0x5d, 0x69, 0xf8, 0x46, 0xb2, 0xf7, 0x46, 0xff, 0x06,
	0x9c, 0x2e, 0xa1, 0x4e, 0xf4, 0x0e, 0x6c, 0x6c, 0x21, 0xad, 0x38, 0xbd, 0x76, 0x76, 0xb1, 0x86,
	0x3d, 0xb3, 0x27, 0xf8, 0xb7, 0x30, 0x35, 0x7a, 0xb9, 0x14, 0x95, 0xc4, 0xe3, 0x0c, 0xde, 0x80,
	0x33, 0xcb, 0xb2, 0x6f, 0x0b, 0xa1, 0x44, 0x37, 0x00, 0x85, 0x93, 0x8c, 0x29, 0xa6, 0xb5, 0x67,
	0xb1, 0x3e, 0xfb, 0x11, 0x4c, 0x0d, 0xad, 0xed, 0x73, 0x05, 0x13, 0x2e, 0x1f, 0x9a, 0x34, 0x45,
	0x29, 0x35, 0xd9, 0x8e, 0x0d, 0x70, 0xfd, 0xdb, 0x32, 0xa3, 0x3d, 0x60, 0xbd, 0xe2, 0x29, 0x4a,
	0xfa, 0x15, 0xa6, 0xf9, 0x20, 0x2b, 0xfa, 0xba, 0x1d, 0xee, 0x40, 0x88, 0x97, 0x17, 0xc3, 0xe1,
	0xbb, 0xfe, 0x1f, 0x61, 0x9c, 0xeb, 0x4d, 0xd0, 0x73, 0x63, 0x61, 0x16, 0x73, 0x50, 0x18, 0x11,
	0x7a, 0x0b, 0x67, 0x92, 0xad, 0xb0, 0xff, 0x73, 0xbe, 0xdc, 0xa3, 0x3e, 0xd2, 0xfb, 0x06, 0x9e,
	0x6e, 0x0d, 0xb6, 0xcd, 0x8f, 0xd5, 0x06, 0x24, 0x22, 0xf4, 0x33, 0xd8, 0xac, 0xcd, 0xb3, 0x37,
	0x18, 0xec, 0xa1, 0x37, 0x18, 0x06, 0x1f, 0x90, 0xf9, 0x5b, 0x78, 0x95, 0x8a, 0x32, 0xcc, 0xb9,
	0x5a, 0x34, 0x49, 0xb8, 0x61, 0xbc, 0xda, 0xf0, 0x2a, 0xec, 0xbe, 0xc2, 0xef, 0x76, 0x77, 0x4a,
	0xc6, 0xda, 0xe2, 0xc3, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf0, 0x5d, 0xf9, 0xd8, 0xa8, 0x03,
	0x00, 0x00,
}
